services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  # Automatically register all services in the src/ directory
  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
